name: update-data

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # ← これ超重要

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install libs
        run: pip install requests beautifulsoup4

      - name: Run script
        run: python main.py

      - name: Commit & Push
        run: |
          git config user.name "bot"
          git config user.email "bot@example.com"
          git add data.json
          git commit -m "update data" || echo "no changes"
          git push
